#!/usr/bin/env bash
######
# Run gulp in a containter
#
# This script runs a command container, using gulp in a specific folder
#
# The container tries to run gulp $@ in a specified path, which should contain
# a gulpfile.  
# To use it, cd into the folder which has the gulpfile, and run
# the command, passing in any cmd that you want.  the script will map
# the current path (pwd) to /app/gulptarget and run gulp there.
#
# @BUG does not run npm install.  Perhaps use an image
# that already has the node modules that you need in it?
#

source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/config.inc"

# use the run path for execution
PATH_GULP="${PATH_EXECUTION}"

CONTAINER_ARGS="${@:1}"
# echo ">>>>>DOCKER:GULP START [CMD: ${CONTAINER_ARGS}]
# "

docker run --rm -t -i \
    --net "${COMPOSE_NETWORK}" \
    --hostname="${PROJECT}" \
    --volume="${PATH_GULP}:/app/gulptarget" \
    --entrypoint="/usr/bin/gulp" \
    -w=/app/gulptarget \
    --name="${PROJECT}_composer" \
    ${DOCKER_IMAGE_DEVELOPERTOOL} \
    ${CONTAINER_ARGS}

# echo "
# <<<<<DOCKER:GULP END "